Vagrant.configure(2) do |config|
  config.vm.box = "win2012r2"

  config.vm.communicator = "winrm"
  config.winrm.username = "Administrator"
  config.winrm.password = "v"
  #config.vm.guest = :windows
  #config.winrm.transport = :plaintext
  #config.winrm.port = "45985"
  #config.winrm.guest_port = "5985"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = 10240
  	vb.cpus = 8
  	vb.customize ["setextradata", :id, "GUI/ShowMiniToolBar", "false"]
  	vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  	vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    #vb.customize ["modifyvm", :id, '--audio', 'dsound', '--audiocontroller', 'HDA']
    vb.customize ["modifyvm", :id, '--audio', 'none']
  end

  #config.vm.network "private_network", type: :dhcp
  #config.vm.network :forwarded_port, guest: 5985, host:45985, id: "winrm", auto_correct: true
  #config.vm.network :forwarded_port, guest: 3389, host: 43389, id: "rdp", auto_correct: true
  
  config.vm.provision "file", source: "configs/.gitconfig", destination: "~/.gitconfig"
  config.vm.provision "shell", "path": "shell/provision.ps1"
end
