Vagrant.configure(2) do |config|
  config.vm.box = "win2012r2"
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = 6144
	vb.cpus = 4
	vb.customize ["setextradata", :id, "GUI/ShowMiniToolBar", "false"]
	vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
	vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
  end
  
  config.vm.provision :shell, :path => "shell/provision.ps1"
  
end
